name: app_barber_shop
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.0.0
  url_launcher: ^6.0.9
  table_calendar: ^3.1.3  
  intl: ^0.19.0  
  syncfusion_flutter_calendar: ^28.2.9
  flutter_calendar_carousel: ^2.4.4
  flutter_form_builder: ^10.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/logo.png
    - assets/barber.png
    - assets/carlos.png
    - assets/eduardo.png
    - assets/paulo.png
    - assets/antonio.jpg
